repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.10  # Use the latest version
    hooks:
      - id: ruff-check
        types_or: [ python, pyi ] 
        args: [ --fix ] # Automatically fix lint errors if possible
      - id: ruff-format
